class MockConfig {
  constructor(serverAdminRole, botAdminIds, helpCommandAliases, commandsToGenerateHelpFor) {
    this.botAdminIds = botAdminIds;
    this.serverAdminRoleName = serverAdminRole;
    this.genericErrorMessage = 'Error';
    this.commandsToGenerateHelpFor = commandsToGenerateHelpFor || [];
    this.autoGeneratedHelpCommandAliases = helpCommandAliases || [];
    this.settingsCommandAliases = [']settings'];
    this.prefixes = ['prefix1', 'prefix2'];
  }
}

module.exports = MockConfig;
