// For intellisense
const discordApiStringForPermission = {
  createInstantInvite: 'createInstantInvite',
  kickMembers: 'kickMembers',
  banMembers: 'banMembers',
  administrator: 'administrator',
  manageChannels: 'manageChannels',
  manageGuild: 'manageGuild',
  addReactions: 'addReactions',
  readMessages: 'readMessages',
  sendMessages: 'sendMessages',
  sendTTSMessages: 'sendTTSMessages',
  manageMessages: 'manageMessages',
  embedLinks: 'embedLinks',
  attachFiles: 'attachFiles',
  readMessageHistory: 'readMessageHistory',
  mentionEveryone: 'mentionEveryone',
  externalEmojis: 'externalEmojis',
  changeNickname: 'changeNickname',
  manageRoles: 'manageRoles',
  manageWebhooks: 'manageWebhooks',
  manageEmojis: 'manageEmojis',
  all: 'All',
  allGuild: 'All Guild',
  allText: 'All Text',
};

const userStringForPermission = {
  createInstantInvite: 'Create Instant Invite',
  kickMembers: 'Kick Members',
  banMembers: 'Ban Members',
  administrator: 'Administrator',
  manageChannels: 'Manage Channels',
  manageGuild: 'Manage Guild',
  addReactions: 'Add Reactions',
  readMessages: 'Read Messages',
  sendMessages: 'Send Messages',
  sendTTSMessages: 'Send TTS Messages',
  manageMessages: 'Manage Messages',
  embedLinks: 'Embed Links',
  attachFiles: 'Attach Files',
  readMessageHistory: 'Read Message History',
  mentionEveryone: 'Mention Everyone',
  externalEmojis: 'Use External Emojis',
  changeNickname: 'Change Nickname',
  manageRoles: 'Manage Roles',
  manageWebhooks: 'Manage Webhooks',
  manageEmojis: 'Manage Emojis',
};

module.exports = {
  discordApiStringForPermission,
  userStringForPermission,
};
